{{ if .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: prometeo-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{ end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometeo-rulesdecision
spec:
  hosts:
  - "*"
  gateways:
  - prometeo-gateway
  http:
  - match:
    - uri:
        exact: /rulesdecision
    rewrite:
      uri: /
    route:
    - destination:
        host: {{ .Values.rulesdecision.name}}
        port:
          number: {{ .Values.rulesdecision.service.servicePort}}
  - match:
    - uri:
        prefix: /coreDecision
    - uri:
        prefix: /get_status
    - uri:
        prefix: /get_configuration
    - uri:
        prefix: /swaggerui
    - uri:
        prefix: /swagger.json
    route:
    - destination:
        host: {{ .Values.rulesdecision.name}}
        port:
          number: {{ .Values.rulesdecision.service.servicePort}}
