# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
rulesdecision:
  name: rulesdecision
  version: v1
  replicaCount: 1
  image:
    repository: uk.icr.io/prometeo-cluster/rulesdecision
    pullPolicy: Always
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  service:
    servicePort: 8080
istio:
  virtualservices:
    enabled: true
  gateway:
    enabled: false
imagepullsecrets:
  name: default-uk-icr-io

