# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: uk.icr.io/prometeo-cluster/rulesdecision
  tag: latest
  pullSecret: regsecret
  pullPolicy: IfNotPresent
  # for local development against Minikube registry
  #pullPolicy: Never  
rulesdecision:
  name: rulesdecision
  version: v1
  replicaCount: 1
  namespace: default
  image:
    repository: uk.icr.io/prometeo-cluster/rulesdecision
    pullSecret: regsecret
    pullPolicy: IfNotPresent
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
  service:
    servicePort: 8080
istio:
  virtualservices:
    enabled: true
  gateway:
    enabled: false
imagepullsecrets:
  name: default-uk-icr-io

